method: MGNet
resume: False
finetune: False
weight: []
seed: 123
device:
  use_gpu: True
  gpu_ids: '0'
  num_workers: 4
data:
  split: /PATH/TO/front3d/objects
loss_weights:
  chamfer_loss: 1.0
  edge_loss: 0.1
  boundary_loss: 0.5
  face_loss: 0.5
model:
  mesh_reconstruction:
    module: DensTMNet
    loss: SVRLoss
    tmn_subnetworks: 2
    with_edge_classifier: True
    face_samples: 1
optimizer:
  type: Adam
  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0.0
scheduler:
  type: ReduceLROnPlateau
  patience: 20
  factor: 0.5
  threshold: 0.002
train:
  epochs: 100
  freeze: []
  batch_size: 24
val:
  batch_size: 24
test:
  batch_size: 1
log:
  vis_step: 1000
  print_step: 50
  path: out/mgnet_front3d
  save_checkpoint: True
