method: Pano3D
resume: False
finetune: True
weight: [
  'out/relation_scene_gcn/21091021124435/model_best.pth',
  'out/layout_estimation/21022217101943/model_best.pth',
  'out/ldif_igibson/26062012023308/model_best.pth',
]
seed: 123
device:
  use_gpu: True
  gpu_ids: '0'
  num_workers: 0
data:
  split: demo/input
  expand_dis: 0.1
  igibson_obj_dataset: data/igibson_obj
  g_feature_length: 64
  height: 512
  width: 1024
model:
  detector:
    module: Detector2D
    config: 'COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml'
    weight: 'out/detector/detector_mask_rcnn/model_final.pth'
    score_thresh: 0.6
    min_iou: 0.25
    real: False
    pano: True
    cf_thresh: 0.3
    nms_thresh: 0.2
    nms_all_thresh: 0.4
  layout_estimation:
    module: HorizonNet
    loss: HorizonLoss
    backbone: resnet50
    use_rnn: True
  bdb3d_estimation:
    module: Bdb3DNet
    loss: JointLoss
    d_k: 64
    Nr: 16
  shape_encoder:
    module: LIEN
    bottleneck_size: 1536
    shape_code_length: 1344
  shape_decoder:
    module: LDIF
    element_count: 32
    sym_element_count: 16
    implicit_parameter_length: 32
    sym_face: yz
    cuda_kernel: False
    bounding_box: 0.7
    num_samples: 5000
    coarse_grid_spacing: 0.04375
    marching_cube_resolution: 64
train:
  epochs: 35
  freeze: ['bdb3d_estimation', 'shape_encoder', 'shape_decoder']
  batch_size: 16
val:
  batch_size: 16
test:
  batch_size: 1
log:
  vis_step: 1
  print_step: 10
  save_mesh: False
  path: out/pano3d_im3d_trained
  save_checkpoint: False
